
package Paquete;

import java.awt.event.KeyEvent;

public class Pantalla extends javax.swing.JFrame {

    Snake snake;
    // MenuPrincipal principal = new MenuPrincipal();
    
    public Pantalla(String difficult) {
        initComponents();
        this.setLocationRelativeTo(null);
        snake = new Snake (600,30,  difficult, this);
        this.add(snake);
        snake.setBounds(10,10,600,600);
        snake.setOpaque(false);
        
        Fondo fondo =  new Fondo(600,30);
        this.add(fondo);
        fondo.setBounds(10,10,600,600);
        
        this.requestFocus(true);    
        
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Volver.setFocusPainted(false);
        Volver.setFocusable(false);
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(528, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Volver)
                .addContainerGap(574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                snake.cambiarDireccion("left");
                break;
            case KeyEvent.VK_RIGHT:
                snake.cambiarDireccion("right");
                break;
            case KeyEvent.VK_UP:
                snake.cambiarDireccion("up");
                break;
            case KeyEvent.VK_DOWN:
                snake.cambiarDireccion("down");
                break;                           
        }
    }//GEN-LAST:event_formKeyPressed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // principal.setVisible(true);
        // dispose();
    }//GEN-LAST:event_VolverActionPerformed
 // TODO ya no sirve
    public void Iniciar (String difficult){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla(difficult).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    // End of variables declaration//GEN-END:variables
}